// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5B87oi7YsRKaVtwISQyZSWVvLzHbtWjY',
    appId: '1:970197042536:web:2bbe232f769c19534ac2dd',
    messagingSenderId: '970197042536',
    projectId: 'demothreewon',
    authDomain: 'demothreewon.firebaseapp.com',
    storageBucket: 'demothreewon.appspot.com',
    measurementId: 'G-YF7MBL2DW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQo2BnQ3MGAerSEp5-eGqCQ8uaqANTxxw',
    appId: '1:970197042536:android:7802af9e7966e2874ac2dd',
    messagingSenderId: '970197042536',
    projectId: 'demothreewon',
    storageBucket: 'demothreewon.appspot.com',
  );
}
